---
title: "Redox_peptide"
author: "Bridget Bai"
date: "2023-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#GO enrichment
```{r}

GOanalysisGodata <- function(EnrichedDF, GamerCut, ont, nodesize){
  gene2GO_TissueCut <- split((as.character(GamerCut$term_accession)),GamerCut$db_object_id)
  gene2GOb_TissueCut <- gene2GO_TissueCut[-2]
  str(head(gene2GOb_TissueCut))
  geneNames_tissuecut <- names(gene2GOb_TissueCut)
  myInterestingGenes <- EnrichedDF$Gene
  geneList <- factor(as.integer(geneNames_tissuecut %in% myInterestingGenes))
  names(geneList) <- geneNames_tissuecut
  GOdata <- new("topGOdata", ontology = ont, allGenes = geneList, annot = annFUN.gene2GO, nodeSize=nodesize, gene2GO = gene2GOb_TissueCut)
  
  resultFis <- runTest(GOdata, algorithm = "classic", statistic = "fisher")
  test.statF <- new("classicCount", testStatistic = GOFisherTest, name = "Fisher test")
  resultFisher <- getSigGroups(GOdata, test.statF)
  test.statKS <- new("classicScore", testStatistic = GOKSTest, name = "KS tests")
  resultKS <- getSigGroups(GOdata, test.statKS)
  test.statRW <- new("weightCount", testStatistic = GOFisherTest, name = "Fisher test", sigRatio = "ratio")
  resultWeight <- getSigGroups(GOdata, test.statRW)
  GO_result_out <- GenTable(GOdata, classic = resultFisher, KS = resultKS, weight = resultWeight, orderBy = "classic", ranksOf = "classic", topNodes = 20)
}
```

```{r}
redox_HMP <- read.csv("~/Desktop/HMP_redox_peptide.csv")
redox_HMP <- redox_HMP[-grep("only",redox_HMP$Accession),]
redox_HMP$Gene <- substr(redox_HMP$Accession, start = 1, stop = 14)
redox_red <- redox_HMP[,c(1:3,20:25,28)]
redox_red <- redox_red[-grep("DIV",redox_red$X6Hybrid.B73xMo17.Hyb.MP.Reduced),]
redox_red_AMP <- redox_red[which(rowSums(redox_red[,4:9]>1) == 6),]
redox_red_BMP <- redox_red[which(rowSums(redox_red[,4:9]<1) == 6),]
redox_red_het <- redox_HMP[,c(1:3,20:21,23:24,28)]
redox_red_het <- redox_red_het[-grep("DIV",redox_red_het$X6Hybrid.B73xMo17.Hyb.MP.Reduced),]
redox_red_het_AMP <- redox_red_het[which(rowSums(redox_red_het[,4:7]>1) ==4),]
redox_red_het_BMP <- redox_red_het[which(rowSums(redox_red_het[,4:7]<1) ==4),]

redox_red_nonhet_AMP <- redox_red[which(rowSums(redox_red[,c(6,9)]>1) == 2),]
redox_red_nonhet_AMP <- redox_red_nonhet_AMP[which(rowSums(redox_red_nonhet_AMP[,c(4:5,7:8)] <1) ==4),]
redox_red_nonhet_BMP <- redox_red[which(rowSums(redox_red[,c(6,9)]<1) == 2),]
redox_red_nonhet_BMP <- redox_red_nonhet_BMP[which(rowSums(redox_red_nonhet_BMP[,c(4:5,7:8)] >1) ==4),]

redox_GO_BP <- GOanalysisGodata(redox_cor_sig,gamercut,"BP",nodesize = 1)
redox_GO_MF <- GOanalysisGodata(redox_red_AMP,gamercut,"MF",nodesize = 1)

redox_red[,4:9] <- as.numeric(unlist(redox_red[,4:9]))
redox_red_t <- t(redox_red[,4:9])
redox_red_cor_height <- data.frame(cor(as.matrix(t(redox_red[,4:9])), hyb_traits[1:6,2]))
colnames(redox_red_cor_height)[1] <- "Cor"
redox_red$cor_height <- redox_red_cor_height$Cor
redox_red$pval <- corPvalueStudent(redox_red$cor_height,nSamples = 6)
redox_red_cor_selected <- redox_red[redox_red$pval < 0.05 & redox_red$cor_height>0,]


```

#comparing inbreds to hybrids
```{r}
redox_all <- read.csv("~/Downloads/redox_red_all.csv")
redox_all[redox_all == 0] <- NA
redox_all <- na.omit(redox_all)
redox_all <- redox_all[-grep("only", redox_all$Accession),]
redox_all <- redox_all[-grep("reverse", redox_all$Accession),]
redox_all$Gene <- substr(redox_all$Accession, start = 1, stop = 14)
redox_all$ttest_r1 <- ttestFun(redox_all, 4:7, 8:13)
redox_all$inbred_mean_r1 <- rowMeans(redox_all[,4:7])
redox_all$hyb_mean_r1 <- rowMeans(redox_all[,8:13])
redox_all$ttest_r2 <- ttestFun(redox_all, 14:17, 18:23)
redox_all$inbred_mean_r2 <- rowMeans(redox_all[,14:17])
redox_all$hyb_mean_r2 <- rowMeans(redox_all[,18:23])
redox_all$ttest_r3 <- ttestFun(redox_all, 24:27, 28:33)
redox_all$inbred_mean_r3 <- rowMeans(redox_all[,24:27])
redox_all$hyb_mean_r3 <- rowMeans(redox_all[,28:33])
redox_all_selected <-redox_all[which(rowSums(redox_all[,c(35,38,41)] < 0.05) ==1),]
plant_height <- read.csv("~/Downloads/6HPlantHeights.csv")
plant_height <- t(plant_height)
colnames(plant_height) <- plant_height[1,]
plant_height <- plant_height[-1,]
plant_height <- data.frame(plant_height)
plant_height[,1:2] <- as.numeric(unlist(plant_height[,1:2]))

redox_all$B73_mean <- rowMeans(redox_all[,c(4,14,24)],na.rm = T)
redox_all$B84_mean <- rowMeans(redox_all[,c(5,15,25)],na.rm = T)
redox_all$Mo17_mean <- rowMeans(redox_all[,c(6,16,26)],na.rm = T)
redox_all$A682_mean <- rowMeans(redox_all[,c(7,17,27)],na.rm = T)
redox_all$B73xMo17_mean <- rowMeans(redox_all[,c(8,18,28)],na.rm = T)
redox_all$Mo17xB73_mean <- rowMeans(redox_all[,c(9,19,29)],na.rm = T)
redox_all$B73xB84_mean <- rowMeans(redox_all[,c(10,20,30)],na.rm = T)
redox_all$B84xMo17_mean <- rowMeans(redox_all[,c(11,21,31)],na.rm = T)
redox_all$A682xB73_mean <- rowMeans(redox_all[,c(12,22,32)],na.rm = T)
redox_all$A682xMo17_mean <- rowMeans(redox_all[,c(13,23,33)],na.rm = T)

redox_all_num <- redox_all[-which(rowSums(redox_all[,44:53]) ==0),c(1:3,44:53)]
redox_all_cor_height <- cor(t(redox_all_num[1:612,4:13]),plant_height$plant.height)
redox_all_num$cor_to_height <- redox_all_cor_height
redox_all_num$pval <- corPvalueStudent(redox_all_num$cor_to_height,nSamples = 10)
redox_cor_sig <- redox_all_num[redox_all_num$pval < 0.05 & redox_all_num$cor_to_height > 0,]
redox_cor_sig$Gene <- substr(redox_cor_sig$Accession, start = 1, stop = 14)

```

```{r}
redox_ox <- redox_HMP[,c(1:3,12:17,28)]
redox_ox <- redox_ox[-grep("DIV",redox_ox$X6Hybrid.B73xMo17.Hyb.MP.Oxidized),]
redox_ox_AMP <- redox_ox[which(rowSums(redox_ox[,4:9]>1) == 6),]
redox_ox_BMP <- redox_ox[which(rowSums(redox_ox[,4:9]<1) == 6),]
redox_ox_het <- redox_HMP[,c(1:3,12:13,15:16,28)]
redox_ox_het <- redox_ox_het[-grep("DIV",redox_ox_het$X6Hybrid.B73xMo17.Hyb.MP.Oxidized),]
redox_ox_het_AMP <- redox_ox_het[which(rowSums(redox_ox_het[,4:7]>1) ==4),]
redox_ox_het_BMP <- redox_ox_het[which(rowSums(redox_ox_het[,4:7]<1) ==4),]
redox_ox_GO_BP <- GOanalysisGodata(redox_ox_cor_selected,gamercut, "BP", nodesize = 1)

redox_ox[,4:9] <- as.numeric(unlist(redox_ox[,4:9]))
redox_ox_t <- t(redox_ox[,4:9])
redox_ox_cor_height <- data.frame(cor(as.matrix(t(redox_ox[,4:9])), hyb_traits[1:6,2]))
colnames(redox_ox_cor_height)[1] <- "Cor"
redox_ox$cor_height <- redox_ox_cor_height$Cor
redox_ox$pval <- corPvalueStudent(redox_ox$cor_height,nSamples = 6)
redox_ox_cor_selected <- redox_ox[redox_ox$pval < 0.05 & redox_ox$cor_height<0,]
```



```{r}
m6A_supp[which(duplicated(m6A_supp$`Gene ID`)),]
m6A_sense <- m6A_supp[m6A_supp$Strand == "+",]
m6A_antisense <- m6A_supp[m6A_supp$Strand == "-",]
intersect(m6A_antisense$`Gene ID`, m6A_sense$`Gene ID`)
m6A_supp[,7:9] <- as.numeric(unlist(m6A_supp[,7:9]))
m6A_level <- read.csv("~/Downloads/m6A_HMP_maize.csv", header = F, stringsAsFactors = F)
m6A_level_HMP <- m6A_level[3:12853, c(1,30,31,35)]
colnames(m6A_level_HMP) <- m6A_level_HMP[1,]
m6A_level_HMP <- m6A_level_HMP[-1,]
mRNA_abundance <- read.csv("~/Downloads/mRNA_abundance_maize.csv", header = F, stringsAsFactors = F)
colnames(mRNA_abundance) <- mRNA_abundance[2,]
mRNA_abundance <- mRNA_abundance[-(1:2),-(6:8)]
transl_efficiency <- read.csv("~/Downloads/translational_efficiency_maize.csv", header = F, stringsAsFactors = F)
colnames(transl_efficiency) <- transl_efficiency[2,]
transl_efficiency <- transl_efficiency[-(1:2),]
m6A_HMP <- merge.data.frame(m6A_level_HMP, mRNA_abundance[,c(1,5)], by.x = "Gene ID", by.y = "Gene ID")
m6A_HMP <- merge.data.frame(m6A_HMP, transl_efficiency[,c(1,5)], by.x = "Gene ID", by.y = "Gene ID")
m6A_HMP <- merge.data.frame(m6A_HMP, seedling_mature_leaf[,c("Gene","Accession","SeedlingLeaf.BM.MP","Protein","SeedlingLeaf.B73.Mo17")], by.x = "Gene ID", by.y = "Gene", all.x = T)
m6A_HMP <- m6A_HMP[-grep("only",m6A_HMP$Accession),]
m6A_HMP <- m6A_HMP[-grep("reverse",m6A_HMP$Accession),]

m6A_HMP$cpm_SL <- cpm.SL[match(m6A_HMP$`Gene ID`, cpm.SL$Gene),"B73xMo17.MP"]
m6A_HMP$cpm_PP <- cpm.SL[match(m6A_HMP$`Gene ID`, cpm.SL$Gene),"B73.Mo17"]
```

